config/routes.rb
Rails.application.routes.draw do

  resources :lenses do
    resources :bookings, only: [:index, :new, :create]
  end
  resources :bookings, only: [:edit, :update, :destroy]

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'

end

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-50deg, rgba(0, 0, 0, 1) 0%, rgba(0,36,61,0.6) 30%), url('http://res.cloudinary.com/tanjamiee/image/upload/v1502791385/wood-coffee-camera-desk-16510_1_slbzoj.jpg');">
  <div class="banner-content">
    <h1>See the world with different lenses</h1>
    <p>With a click, in a snap</p>

    <div class="search">
    <%= form_tag lenses_path, method: 'get', class: 'navbar-form navbar-center' do %>
    <input type="hidden" name="search" value="true">
      <label>Location:</label>
      <select type="search" name="location" >
        <option disabled selected>City</option>
        <option>Chengdu</option>
        <option>Shanghai</option>
        <option>Suzhou</option>
        <option>Beijing</option>
        <option>Xinjiang</option>
        <option>Shenzhen</option>
        <option>Guangzhou</option>
      </select>

      <label>Type:</label>
      <select type="search" name="lens_type">
        <option disabled selected>Lens type</option>
        <option>Kit</option>
        <option>Standard</option>
        <option>Prime</option>
        <option>Telephoto Zoom</option>
        <option>Macro</option>
        <option>Wide Angle</option>
      </select>

      <label>Brand:</label>
      <select type="search" name="brand">
        <option disabled selected>Lens brand</option>
        <option>Canon</option>
        <option>Leica</option>
        <option>Minolta</option>
        <option>Nikon</option>
        <option>Olympus</option>
      </select>
      <br>
      <label>Max Price: $</label>
      <input type="number" name="price" placeholder="$200">
      <label type="search">Borrow date:</label>
      <input id="borrow_date" name="borrow_date" min="2017-01-01" max="2018-01-01" type="date">
      <label type="search">Return date:</label>
      <input id="return_date" name="return_date" min="2017-01-01" max="2018-01-01" type="date">
      <br>
      <br>
      <button>Search</button>
    </div>
    <p>or <%= button_to "Browse all", "lenses?utf8=✓&search=true&location=&price=&borrow_date=&return_date=", {class: "btn btn-basic"} %><p>
    <% end %>
  </div>
</div>

app/views/pages/_cards.html.erb
<div class="cards">
  <div class="container">
    <div class="row">
     <% if @lenses.blank? %>
     <p>No lenses to show</p>
     <% else %>
      <% @lenses.each do |lense| %>
        <%= link_to lense do %>
        <div class="col-xs-12 col-sm-4">
          <div class="outer-card">
            <div class="card-content">
              <h4><%= lense.brand %></h4>
              <p style="font-size: 12px"><%=lense.lens_type %></p>
              <p><%= "$" + ('%.2f' % lense.price) + "/day" %></p>
              <p><%= lense.location %></p>
            </div>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path lense.photo.url, width: 250, height: 250, crop:"fit" %>);">
            </div>
          </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/pages/_cards_with_delete.html.erb
<div class="cards">
  <div class="container">
    <div class="row">
     <% if @lenses.blank? %>
        <div class="col-xs-9">
            <div class="card-content">
              <p>No lenses to show. Click 'Add a lens listing' on the navigation bar to add a lens!</p>
            </div>
         </div>
     <% else %>
      <% @lenses.each do |lense| %>
        <%= link_to lense do %>
        <div class="col-xs-12 col-sm-4">
          <div class="outer-card">
            <div class="card-content">
              <h4><%= lense.brand %></h4>
              <p style="font-size: 12px"><%=lense.lens_type %></p>
              <p><%= lense.location %></p>
            </div>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path lense.photo.url, width: 250, height: 250, crop:"fit" %>);">
            </div>

        </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<br>
<div class="container text-center grid">
  <div class="gridcard grid-avatar">
    <div class="gridcard-content">
        <h1>My Listings </h1>
        <%= render "pages/cards_with_delete" %>
      </div>
    </div>

  <div class="gridcard grid-booking">
    <div class="gridcard-content">
      <h2>Bookings Received</h2>
    </div>
  </div>

  <div class="gridcard grid-booking-pending">
    <div class="gridcard-content">
      <h3>Pending</h3>
        <% if @bookings_received_pending.blank? %>
          <p>None</p>
        <% end %>
        <% @bookings_received_pending.each do |booking| %>
          <p><%= "Your " + booking.lense.brand + " " + booking.lense.lens_type + " lens in " + booking.lense.location %> | <%= link_to "Respond to request", edit_booking_path(booking) %></p>
        <% end %>
    </div>
  </div>

  <div class="gridcard grid-booking-approved">
    <div class="gridcard-content">
      <h3>Approved</h3>
      <% if @bookings_received_approved.blank? %>
        <p>None</p>
      <% end %>
      <% @bookings_received_approved.each do |booking| %>
        <p><%= "Your " + booking.lense.brand + " " + booking.lense.lens_type + " lens in " + booking.lense.location %> | <%= link_to "Edit approval", edit_booking_path(booking) %></p>
      <% end %>
    </div>
  </div>

  <div class="gridcard grid-booking-rejected">
    <div class="gridcard-content">
      <h3>Rejected</h3>
      <% if @bookings_received_rejected.blank? %>
        <p>None</p>
      <% end %>
      <% @bookings_received_rejected.each do |booking| %>
        <p><%= "Your " + booking.lense.brand + " " + booking.lense.lens_type + " lens in " + booking.lense.location %> | <%= link_to "Edit rejection", edit_booking_path(booking) %></p>
      <% end %>
    </div>
  </div>

  <div class="gridcard grid-request">
    <div class="gridcard-content">
      <h2>Bookings Requested</h2>
    </div>
  </div>

  <div class="gridcard grid-request-pending">
    <div class="gridcard-content">
      <h3>Pending</h3>
      <% if @bookings_requested_pending.blank? %>
        <p>None</p>
      <% end %>
      <% @bookings_requested_pending.each do |booking| %>
        <p data-booking-id="<%= booking.id %>"><%= booking.lense.user.first_name + "'s " + booking.lense.brand + " " + booking.lense.lens_type + " lens in " + booking.lense.location %> | <%= link_to "Delete", booking, method: :delete, remote: true %></p>
      <% end %>
    </div>
  </div>

  <div class="gridcard grid-request-approved">
    <div class="gridcard-content">
      <h3>Approved</h3>
      <% if @bookings_requested_approved.blank? %>
        <p>None</p>
      <% end %>
      <% @bookings_requested_approved.each do |booking| %>
        <p><%= booking.lense.user.first_name + "'s " + booking.lense.brand + " " + booking.lense.lens_type + " lens in " + booking.lense.location %> | <%= link_to "Confirm payment", edit_booking_path(booking) %></p>
      <% end %>
    </div>
  </div>

  <div class="gridcard grid-request-rejected">
    <div class="gridcard-content">
      <h3>Rejected</h3>
      <% if @bookings_requested_rejected.blank? %>
        <p>None</p>
      <% end %>
      <% @bookings_requested_rejected.each do |booking| %>
        <p><%= booking.lense.user.first_name + "'s " + booking.lense.brand + " " + booking.lense.lens_type + " lens in " + booking.lense.location %> | <%= link_to "Edit booking request and resubmit", edit_booking_path(booking) %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render "pages/banner" %>

<div class="container">
  <div class="row">

      <h1>Newest lenses on loan</h1>
    <%= render "pages/cards" %>

  </div>
</div>