config/routes.rb
Rails.application.routes.draw do

  resources :lenses do
    resources :bookings, only: [:index, :new, :create]
  end
  resources :bookings, only: [:edit, :update, :destroy]

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'

end

app/views/layouts/_add_booking_form.html.erb
<%= simple_form_for [@lense, @booking], url: lense_bookings_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :borrow_date, as: :date, order: [:day, :month, :year], placeholder: "Input borrow date" %>
    <%= f.input :return_date, as: :date, order: [:day, :month, :year], placeholder: "Input return date" %>
    <%= f.input :booking_comment, placeholder: "Hi please let me borrow your awesome lenses :)", :input_html => { :style => "width: 100%"  } %>
    <%= f.hidden_field :user_id, value: current_user.id %>

  </div>

  <div class="form-action">
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/layouts/_add_lens_form.html.erb
<%= simple_form_for(@lense) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :lens_type, collection: ["Kit", "Standard", "Prime", "Telephoto Zoom", "Macro", "Wide Angle"], placeholder: "Choose lens type" %>
    <%= f.input :brand, collection: ["Canon", "Leica", "Minolta", "Nikon", "Olympus"], placeholder: "Please choose the brand" %>
    <%= f.input :price, placeholder: "Price per day" %>
    <%= f.input :condition, collection: ["Excellent", "Good", "Usable"],placeholder: "Fungus? Scratches?" %>
    <%= f.input :location, collection: ["Chengdu", "Shanghai", "Suzhou", "Beijing", "Xinjiang", "Shenzhen", "Guangzhou"], placeholder: "Which city is your lens available in?" %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>

  <div class="form-action">
    <%= f.button :submit, "Add lens", class: "btn btn-success btn-block"  %>
  </div>
<% end %>

app/views/layouts/_approve_booking_form.html.erb
<%= simple_form_for @booking, url: booking_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :approved_by_owner, collection: [["Yes", true], ["No", false], ["Respond later", nil]], placeholder: "Do you approve booking request?" %>
    <%= f.hidden_field :user_id, value: current_user.id %>

  </div>

  <div class="form-action">
    <%= f.button :submit, class: "btn btn-primary btn-big"  %>
  </div>
<% end %>

app/views/layouts/_edit_booking_form.html.erb
<%= simple_form_for @booking, url: booking_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :borrow_date, as: :date, order: [:day, :month, :year], placeholder: "Input borrow date" %>
    <%= f.input :return_date, as: :date, order: [:day, :month, :year], placeholder: "Input return date" %>
    <%= f.input :booking_comment, placeholder: "Hi please let me borrow your awesome lenses :)" %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :approved_by_owner, value: nil %>
  </div>

  <div class="form-action">
    <%= f.button :submit, class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/layouts/_edit_lens_form.html.erb
<%= simple_form_for(@lense) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :lens_type, collection: ["Kit", "Standard", "Prime", "Telephoto Zoom", "Macro", "Wide Angle"], value: @lense.lens_type %>
    <%= f.input :brand, collection: ["Canon", "Leica", "Minolta", "Nikon", "Olympus"],value: @lense.brand %>
    <%= f.input :price, value: @lense.price %>
    <%= f.input :condition, collection: ["Excellent", "Good", "Usable"], value: @lense.condition %>
    <%= f.input :location, collection: ["Chengdu", "Shanghai", "Suzhou", "Beijing", "Xinjiang", "Shenzhen", "Guangzhou"], value: @lense.location %>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

    <%= f.input :photo, value: @lense.photo %>
    <%= f.input :photo_cache, as: :hidden %>

  <div class="form-action">
    <%= f.button :submit, class: "btn btn-primary btn-big button-space"  %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>LENDSES</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=#{ENV["GOOGLE_API_BROWSER_KEY"]}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:for_map) %>
  </body>
</html>